name: carbon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  cloud_functions: ^5.6.1

  # UI e Estilo
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_spinkit: ^5.2.1
  animated_text_kit: ^4.2.2
  lottie: ^3.1.2 
  audioplayers: ^6.0.0 

  # Funcionalidades
  provider: ^6.1.2
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  fl_chart: ^0.68.0
  geolocator: ^12.0.0 
  cupertino_icons: ^1.0.6
  flutter_map: ^7.0.0 
  latlong2: ^0.9.1 
  shimmer: ^3.0.0
  percent_indicator: ^4.2.3 
  image_picker: ^1.1.2 
  permission_handler: ^11.3.1
  google_mlkit_text_recognition: ^0.15.0
  http: ^1.2.1 
  url_launcher: ^6.3.0 
  google_sign_in: ^6.2.1
  flutter_stripe: ^11.0.0 
  file_picker: ^8.0.3 
  flutter_svg: ^2.0.10+1
  animated_digit: ^3.2.2
  syncfusion_flutter_charts: ^30.2.7
  
  # MUDANÇA: Movido de dev_dependencies e adicionado 'js'
  shared_preferences: ^2.2.3
  js: ^0.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/images/