name: carbon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0 
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5

  # UI e Estilo
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_spinkit: ^5.2.1
  animated_text_kit: ^4.2.2
  lottie: ^3.0.0
  audioplayers: ^5.2.1

  # Funcionalidades
  provider: ^6.1.2
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  fl_chart: ^0.68.0
  geolocator: ^11.1.0
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.10.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  shimmer: ^3.0.0
  percent_indicator: ^4.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
