// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7h2B1aDBSln6f4GAnUdV9H4XoQ2w1_-0',
    appId: '1:881045701473:web:02082402fca3e5766f7b20',
    messagingSenderId: '881045701473',
    projectId: 'carbono-tracker-app',
    authDomain: 'carbono-tracker-app.firebaseapp.com',
    storageBucket: 'carbono-tracker-app.firebasestorage.app',
    measurementId: 'G-TGG27LN7R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJSOP9nzPOUj1Ph-wGCtvSB9C-acF3mAM',
    appId: '1:881045701473:android:7ba1d7874ff779a76f7b20',
    messagingSenderId: '881045701473',
    projectId: 'carbono-tracker-app',
    storageBucket: 'carbono-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoVnGjeEEdcytiQ-t4mQDUciRKKtd3pp0',
    appId: '1:881045701473:ios:90233da05d354f546f7b20',
    messagingSenderId: '881045701473',
    projectId: 'carbono-tracker-app',
    storageBucket: 'carbono-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.carbon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoVnGjeEEdcytiQ-t4mQDUciRKKtd3pp0',
    appId: '1:881045701473:ios:90233da05d354f546f7b20',
    messagingSenderId: '881045701473',
    projectId: 'carbono-tracker-app',
    storageBucket: 'carbono-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.carbon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7h2B1aDBSln6f4GAnUdV9H4XoQ2w1_-0',
    appId: '1:881045701473:web:072e1904d6ae94cb6f7b20',
    messagingSenderId: '881045701473',
    projectId: 'carbono-tracker-app',
    authDomain: 'carbono-tracker-app.firebaseapp.com',
    storageBucket: 'carbono-tracker-app.firebasestorage.app',
    measurementId: 'G-B8D2C5HT4P',
  );
}
